"""add ad model

Revision ID: 2ecd4c73cbc9
Revises: 208b19d0bf40
Create Date: 2025-08-18 11:16:56.842399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ecd4c73cbc9'
down_revision = '208b19d0bf40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=False),
    sa.Column('destination_url', sa.String(length=200), nullable=False),
    sa.Column('placement', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ads')
    # ### end Alembic commands ###
