"""Add is_active and created_at to User model

Revision ID: 5e713e2af4e0
Revises: 4668e27d076b
Create Date: 2025-08-17 12:31:57.248881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e713e2af4e0'
down_revision = '4668e27d076b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('created_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DATETIME(), nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
