"""Add category to Post model

Revision ID: f1432b5a6873
Revises: 5e713e2af4e0
Create Date: 2025-08-17 14:35:19.560061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1432b5a6873'
down_revision = '5e713e2af4e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    op.execute("UPDATE posts SET category = 'general' WHERE category IS NULL")

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.String(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
